<?php

$cart = $this->cart;

$items = $cart->getItems();

$paymentMethods = $this->paymentMethods;

?>
<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
	->appendFile('/js/checkout.js')
;
?>
<div id="view-content">
	<?php foreach ($items as $item):
			$product = $item[0];
			$count   = $item[1];
		?>
		<div class="product">
			<?=$product->getTitle();?>
			&nbsp;
			<input type="text" value="<?=$count;?>" style="width: 2em;"/>
			&nbsp;
			<?=$product->getCost() * $count;?>
			&nbsp;
		</div>
	<?php endforeach; ?>

	<form method="post" action="/cart/checkout">
		<fieldset>
			<label>Итого: <input type="text" value="<?= $cart->getSum(); ?>"></label><br>
			<label><input type="radio" name="pp" value="1" checked="checked"/> Robox</label>
			<label><input type="radio" name="pp" value="2"/> Кто-то еще</label>

			<?php if($paymentMethods):
					foreach($paymentMethods as $method):
				?>
						<img width="100" height="50" src="/i/<?=$method['logotype']?$method['logotype']:'dot.gif'?>"/>
					<label><input type="radio" name="payment_method"
								  value="<?=$method['id']?>"/><?=$method['title']?> </label><br/>
			<?php 	endforeach;
					endif; ?>
			<button>Оплатить</button>
		</fieldset>
	</form>

</div>
